#include "levelset.h"
#include <chthon/test.h>

static const char * xml[] =  
"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
"<SokobanLevels xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"SokobanLev.xsd\">\n"
"  <Title>Microban II</Title>\n"
"  <Description>\n"
"Microban II (135 puzzles released April, 2002) Like Microban, this set\n"
"is for beginners and children. Most of the puzzles are small and\n"
"illustrate a particular concept. At the end of the set are four &quot;mega&quot;\n"
"puzzles which are fun to watch on programs which can handle oversize\n"
" levels and allow &quot;automated extended pushes&quot;.\n"
"  </Description>\n"
"  <Email>sasquatch@bentonrea.com</Email>\n"
"  <Url>http://users.bentonrea.com/~sasquatch/sokoban/</Url>\n"
"  <LevelCollection Copyright=\"David W Skinner\" MaxWidth=\"47\" MaxHeight=\"41\">\n"
"    <Level Id=\"1\" Width=\"6\" Height=\"8\">\n"
"      <L>####</L>\n"
"      <L>#  #</L>\n"
"      <L>#  #</L>\n"
"      <L>#  ###</L>\n"
"      <L>#.$ @#</L>\n"
"      <L>#    #</L>\n"
"      <L>#  ###</L>\n"
"      <L>####</L>\n"
"    </Level>\n"
"    <Level Id=\"2\" Width=\"6\" Height=\"17\">\n"
"      <L> #####</L>\n"
"      <L> #   #</L>\n"
"      <L>## # #</L>\n"
"      <L>#  @ #</L>\n"
"      <L>#  $ #</L>\n"
"      <L># #.##</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#   #</L>\n"
"      <L>#####</L>\n"
"    </Level>\n"
"    <Level Id=\"3\" Width=\"7\" Height=\"8\">\n"
"      <L>   ####</L>\n"
"      <L>####  #</L>\n"
"      <L>#  #  #</L>\n"
"      <L>#     #</L>\n"
"      <L># @$. #</L>\n"
"      <L># # ###</L>\n"
"      <L>#   #</L>\n"
"      <L>#####</L>\n"
"    </Level>\n"
"  </LevelCollection>\n"
" </SokobanLevels>\n"

SUITE(levelset) {

}
